// Generated by CoffeeScript 1.10.0
(function() {
  var setElementsProject;

  setElementsProject = setInterval((function() {
    if (!_.isUndefined(window.legends) && !_.isUndefined(window.elementsProject)) {
      $('[data-toggle="popover"]').popover();
      clearInterval(setElementsProject);
    }
  }), 100);

}).call(this);

//# sourceMappingURL=elements-project.js.map
