// Generated by CoffeeScript 1.10.0
(function() {
  var setSidebar;

  setSidebar = setInterval((function() {
    var compiled, compiledHelp, compiledLegend;
    if (!_.isUndefined(window.legends)) {
      compiled = _.template(CoreView.template(BASE_URL + '/tpls/sidebar/project-elements.tpl'));
      $('#project-elements').html(compiled({
        enterprises: window.enterprises
      }));
      compiledHelp = _.template(CoreView.template(BASE_URL + '/tpls/sidebar/help.tpl'));
      $('#help').html(compiledHelp());
      compiledLegend = _.template(CoreView.template(BASE_URL + '/tpls/sidebar/legend.tpl'));
      $('#legend').html(compiledLegend({
        geoServerLegendLink: window.geoServerLegendLink,
        "legends": window.legends
      }));
      clearInterval(setSidebar);
    }
  }), 100);

}).call(this);

//# sourceMappingURL=sidebar.js.map
