// Generated by CoffeeScript 1.10.0
(function() {
  var compiled, compiledHelp;

  console.log(window.enterprises);

  compiled = _.template(CoreView.template(BASE_URL + '/tpls/sidebar/project-elements.tpl'));

  $('#project-elements').html(compiled({
    enterprises: window.enterprises
  }));

  compiledHelp = _.template(CoreView.template(BASE_URL + '/tpls/sidebar/help.tpl'));

  $('#help').html(compiledHelp());

}).call(this);

//# sourceMappingURL=sidebar.js.map
