// Generated by CoffeeScript 1.10.0
(function() {
  var setThematicMap;

  setThematicMap = setInterval((function() {
    if (!_.isUndefined(window.legends) && !_.isUndefined(window.elementsProject)) {
      $('.toggle-thematic-map').click(function() {
        var i, id, layer, len, ref, results;
        id = $(this).attr('id');
        ref = window.layers;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          layer = ref[i];
          if (!_.isUndefined(layer.get('thematicMap'))) {
            results.push(layer.set('visible', id === layer.get('id')));
          } else {
            results.push(void 0);
          }
        }
        return results;
      });
      clearInterval(setThematicMap);
    }
  }), 100);

}).call(this);

//# sourceMappingURL=thematic-map.js.map
