// Generated by CoffeeScript 1.10.0
(function() {
  var setThematicMap;

  setThematicMap = setInterval((function() {
    if (!_.isUndefined(window.legends) && !_.isUndefined(window.elementsProject)) {
      $('.toggle-thematic-map').click(function() {
        var layer;
        layer = _.find(window.layers, function(layer) {
          if (layer.get('id') === $(this).attr('id')) {
            return true;
          } else {
            return layer.setVisible(false);
          }
        });
        layer.setVisible(true);
        window.map.removeLayer(layer);
        return window.map.addLayer(layer);
      });
      clearInterval(setThematicMap);
    }
  }), 100);

}).call(this);

//# sourceMappingURL=thematic-map.js.map
